apiVersion: apps/v1
kind: Deployment
metadata:
 name: uberbe
spec:
 selector:
  matchLabels:
   app: uberbe
 replicas: 3
 minReadySeconds: 15
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1
 template:
  metadata:
   labels:
    app: uberbe
  spec:
   containers:
   - image: 211252803163.dkr.ecr.us-east-1.amazonaws.com/uberbe:prod
     imagePullPolicy: Always
     name: uberbe
     ports:
     - containerPort: 5000
